import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  TrendingUp,
  TrendingDown,
  Minus,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  Plus,
  X,
  UserPlus,
  Phone,
  Building2,
  Target,
  Circle,
  CheckCircle2,
  Trophy,
  Clock,
  BellRing,
  ArrowRight,
  Calendar,
  Sun,
  Eye,
  Users,
} from "lucide-react";
import { useState, useEffect, useMemo } from "react";
import { formatDistanceToNow, format, parseISO, differenceInDays, isToday, isYesterday } from "date-fns";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn, formatCurrency, formatShortCurrency, STAGE_LABELS } from "@/lib/utils";
import type { ActivityLog, Task, Client, ClientContact, Lead } from "@shared/schema";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { useAuth } from "@/hooks/use-auth";
import { QuickActionsBar } from "@/components/QuickActionsBar";
import { apiRequest, queryClient } from "@/lib/queryClient";

interface DashboardStats {
  activeLeads: number;
  activeLeadsCRM: number;
  activeLeadsBuildOps: number;
  pipelineValue: string;
  openTasks: number;
  tasksDueToday: number;
  monthlyRevenue: string;
  leadStageCounts: { stage: string; count: number }[];
  winRate: number | null;
  overdueTasks: number;
  revenueByMonth: { month: string; revenue: string }[];
  estimateStatusCounts: { status: string; count: number }[];
  mrr: string;
}

const CLOSED_STAGES = new Set(["won", "lost", "closed_lost"]);

const monthLabel = (yearMonth: string) => {
  try {
    return format(parseISO(`${yearMonth}-01`), "MMM");
  } catch {
    return yearMonth;
  }
};

function getHealthColor(score: number | null): string {
  if (score === null) return "bg-muted text-muted-foreground";
  if (score >= 70) return "bg-green-100 text-green-700";
  if (score >= 40) return "bg-amber-100 text-amber-700";
  return "bg-red-100 text-red-700";
}

function TrendArrow({ trend }: { trend: string | null }) {
  if (trend === "rising") return <TrendingUp className="h-3.5 w-3.5 text-green-600 shrink-0" />;
  if (trend === "declining") return <TrendingDown className="h-3.5 w-3.5 text-red-500 shrink-0" />;
  return <Minus className="h-3.5 w-3.5 text-muted-foreground shrink-0" />;
}

function getSuggestedAction(
  client: Client,
  openQuoteClientIds: Set<number>,
): { label: string; color: string } {
  const lastContact = client.lastContactDate ? new Date(client.lastContactDate) : null;
  const daysSinceContact = lastContact ? differenceInDays(new Date(), lastContact) : null;

  if (daysSinceContact !== null && daysSinceContact > 30) {
    return { label: "Send check-in email", color: "bg-blue-100 text-blue-700" };
  }
  if (client.healthTrend === "declining") {
    return { label: "Score declining — review account", color: "bg-red-100 text-red-700" };
  }
  if (openQuoteClientIds.has(client.id)) {
    return { label: "Follow up on expired quote", color: "bg-amber-100 text-amber-700" };
  }
  if (!client.totalJobCount || client.totalJobCount === 0) {
    if (daysSinceContact === null || daysSinceContact > 60) {
      return { label: "No recent work — reconnect", color: "bg-orange-100 text-orange-700" };
    }
  }
  return { label: "On track", color: "bg-green-100 text-green-700" };
}

function computePhaseMillestones(
  client: Client,
  hasContact: boolean,
  hasDeal: boolean,
): number {
  let done = 1; // account created
  if (hasContact) done++;
  if (hasDeal) done++;
  if ((client.totalJobCount ?? 0) > 0) done++;
  if (client.avgMonthlyRevenue && Number(client.avgMonthlyRevenue) > 0) done++;
  if (client.lastContactDate) done++;
  if (client.healthScore !== null) done++;
  return done;
}

const AUTO_TASK_PREFIXES = [
  "At-Risk Alert:",
  "Declining Account:",
  "No Contact:",
  "Unresponsive Quote:",
];

function isAutoGeneratedTask(task: Task): boolean {
  return AUTO_TASK_PREFIXES.some(prefix => task.title.startsWith(prefix));
}

function getAlertType(title: string): string {
  if (title.startsWith("At-Risk Alert:")) return "At-Risk";
  if (title.startsWith("Declining Account:")) return "Declining";
  if (title.startsWith("No Contact:")) return "No Contact";
  if (title.startsWith("Unresponsive Quote:")) return "Expired Quote";
  return "Alert";
}

const ALERT_COLORS: Record<string, string> = {
  "At-Risk": "bg-red-100 text-red-700 border-red-200",
  "Declining": "bg-orange-100 text-orange-700 border-orange-200",
  "No Contact": "bg-blue-100 text-blue-700 border-blue-200",
  "Expired Quote": "bg-amber-100 text-amber-700 border-amber-200",
};

export default function Dashboard() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const [pipelineExpanded, setPipelineExpanded] = useState(false);
  const [overdueMilestonesExpanded, setOverdueMilestonesExpanded] = useState(false);
  const [quickAction, setQuickAction] = useState<"deal" | "contact" | "company" | "task" | "activity" | null>(null);
  const [onboardingSteps, setOnboardingSteps] = useState<Record<string, boolean>>({});
  const [isDismissed, setIsDismissed] = useState(false);

  const isAdminOrManager = user && ["super_admin", "admin", "manager"].includes(user.role ?? "");
  const [viewTeamId, setViewTeamId] = useState<string>("__all__");
  const [viewUserId, setViewUserId] = useState<string>("__all__");

  const { data: teamsList = [] } = useQuery<{ id: number; name: string }[]>({
    queryKey: ["/api/teams"],
    enabled: !!isAdminOrManager,
  });

  const { data: userDirectory = [] } = useQuery<{ id: string; firstName: string | null; lastName: string | null; email: string }[]>({
    queryKey: ["/api/users/directory"],
    enabled: !!isAdminOrManager,
  });

  const dashboardQueryKey = useMemo(() => {
    const params = new URLSearchParams();
    if (isAdminOrManager) {
      if (viewTeamId !== "__all__") { params.set("teamId", viewTeamId); }
      else if (viewUserId !== "__all__") { params.set("userId", viewUserId); }
      else { params.set("filter", "all"); }
    } else {
      params.set("filter", "mine");
    }
    return ["/api/dashboard", params.toString()];
  }, [isAdminOrManager, viewTeamId, viewUserId]);

  const { data: stats, isLoading: statsLoading } = useQuery<DashboardStats>({
    queryKey: dashboardQueryKey,
    queryFn: () => {
      const params = new URLSearchParams(dashboardQueryKey[1] as string);
      return fetch(`/api/dashboard?${params.toString()}`, { credentials: "include" }).then(r => r.json());
    },
  });

  const scopeParams = useMemo(() => {
    if (!isAdminOrManager) return "";
    if (viewTeamId !== "__all__") return `?teamId=${viewTeamId}`;
    if (viewUserId !== "__all__") return `?userId=${viewUserId}`;
    return "";
  }, [isAdminOrManager, viewTeamId, viewUserId]);

  const { data: clients = [] } = useQuery<Client[]>({
    queryKey: ["/api/clients", scopeParams],
    queryFn: () => fetch(`/api/clients${scopeParams}`, { credentials: "include" }).then(r => r.json()),
  });
  const { data: contacts = [] } = useQuery<ClientContact[]>({ queryKey: ["/api/client-contacts"] });
  const { data: leads = [] } = useQuery<Lead[]>({
    queryKey: ["/api/leads", scopeParams],
    queryFn: () => fetch(`/api/leads${scopeParams}`, { credentials: "include" }).then(r => r.json()),
  });
  const { data: tasks = [], isLoading: tasksLoading } = useQuery<Task[]>({ queryKey: ["/api/tasks"] });
  const { data: milestoneSummary = {} } = useQuery<Record<number, { completed: number; total: number }>>({
    queryKey: ["/api/clients/milestone-summary", scopeParams],
    queryFn: () => fetch(`/api/clients/milestone-summary${scopeParams}`, { credentials: "include" }).then(r => r.json()),
  });
  const { data: overdueMilestones = [] } = useQuery<{ clientId: number; clientName: string; overdueCount: number }[]>({ queryKey: ["/api/clients/overdue-milestones"] });

  useEffect(() => {
    if (user) {
      const stored = localStorage.getItem(`onboarding_${user.id}`);
      if (stored) setOnboardingSteps(JSON.parse(stored));
      if (localStorage.getItem(`onboarding_${user.id}_dismissed`) === "true") setIsDismissed(true);
    }
  }, [user]);

  const toggleStep = (stepId: string) => {
    const newSteps = { ...onboardingSteps, [stepId]: !onboardingSteps[stepId] };
    setOnboardingSteps(newSteps);
    if (user) localStorage.setItem(`onboarding_${user.id}`, JSON.stringify(newSteps));
  };

  const dismissOnboarding = () => {
    setIsDismissed(true);
    if (user) localStorage.setItem(`onboarding_${user.id}_dismissed`, "true");
  };

  const createTaskMutation = useMutation({
    mutationFn: (data: { title: string; relatedClientId: number; priority: string }) =>
      apiRequest("POST", "/api/tasks", { ...data, status: "todo", sortOrder: 0 }).then(r => r.json()),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/tasks"] }),
  });

  const myClients = useMemo(() =>
    clients.filter(c => c.accountManagerUserId === user?.id),
    [clients, user?.id],
  );

  const atRiskCount = useMemo(() =>
    myClients.filter(c => c.healthScore !== null && c.healthScore < 40).length,
    [myClients],
  );

  const decliningCount = useMemo(() =>
    myClients.filter(c => c.healthTrend === "declining").length,
    [myClients],
  );

  const now = new Date();
  const overdueTasks = useMemo(() =>
    tasks.filter(t =>
      t.assignedTo === user?.id &&
      t.status !== "done" &&
      t.dueDate &&
      new Date(t.dueDate) < now,
    ),
    [tasks, user?.id],
  );

  const todaysAlerts = useMemo(() => {
    const cutoff = new Date(now.getTime() - 26 * 60 * 60 * 1000); // within last 26 hours (covers nightly runs)
    return tasks.filter(t =>
      t.assignedTo === user?.id &&
      isAutoGeneratedTask(t) &&
      t.createdAt &&
      new Date(t.createdAt) > cutoff,
    );
  }, [tasks, user?.id]);

  const sortedMyClients = useMemo(() => {
    const phase1 = myClients.filter(c => (c.customerPhase ?? 1) === 1 || c.healthScore === null);
    const phase2plus = myClients.filter(c => (c.customerPhase ?? 1) > 1 && c.healthScore !== null);
    phase2plus.sort((a, b) => (a.healthScore ?? 999) - (b.healthScore ?? 999));
    return [...phase2plus, ...phase1];
  }, [myClients]);

  const openQuoteClientIds = useMemo(() => {
    const cutoff = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    const ids = new Set<number>();
    leads.forEach(l => {
      if (l.buildopsQuoteId && l.clientId && !CLOSED_STAGES.has(l.stage ?? "") && l.updatedAt && new Date(l.updatedAt) < cutoff) {
        ids.add(l.clientId);
      }
    });
    return ids;
  }, [leads]);

  const clientContactMap = useMemo(() => {
    const map = new Set<number>();
    contacts.forEach(c => map.add(c.clientId));
    return map;
  }, [contacts]);

  const clientDealMap = useMemo(() => {
    const map = new Set<number>();
    leads.forEach(l => { if (l.clientId) map.add(l.clientId); });
    return map;
  }, [leads]);

  const clientMap = useMemo(() =>
    Object.fromEntries(clients.map(c => [c.id, c])),
    [clients],
  );

  const chartData = (stats?.revenueByMonth ?? []).map((r) => ({
    month: monthLabel(r.month),
    revenue: Number(r.revenue),
  }));

  const greeting = (() => {
    const hour = now.getHours();
    if (hour < 12) return "Good morning";
    if (hour < 17) return "Good afternoon";
    return "Good evening";
  })();
  const firstName = user?.firstName ?? user?.email?.split("@")[0] ?? "";

  const onboardingItems = [
    { id: "company", title: "Add your first company", icon: Building2, href: "/customers", done: clients.length > 0 || onboardingSteps["company"] },
    { id: "contact", title: "Add a contact", icon: UserPlus, href: "/customers", done: contacts.length > 0 || onboardingSteps["contact"] },
    { id: "lead", title: "Create your first lead", icon: Target, href: "/leads", done: leads.length > 0 || onboardingSteps["lead"] },
    { id: "activity", title: "Log your first activity", icon: Phone, action: () => setQuickAction("activity"), done: onboardingSteps["activity"] },
  ];

  const completedCount = onboardingItems.filter(item => item.done).length;
  const isNewUser = user && differenceInDays(now, new Date(user.createdAt)) < 7;
  const showOnboarding = isNewUser && !isDismissed && completedCount < 4;

  return (
    <div className="p-4 md:p-6 space-y-6">
      <QuickActionsBar
        showButton={false}
        externalDialog={quickAction === "activity" ? null : quickAction as any}
        onExternalOpen={(d) => setQuickAction(d as any)}
      />

      {/* ── Viewing As (admin/manager only) ──────────────────────────── */}
      {isAdminOrManager && (
        <div className="flex items-center gap-3 bg-muted/50 border border-border/60 rounded-lg px-4 py-2.5">
          <Eye className="h-4 w-4 text-muted-foreground shrink-0" />
          <span className="text-sm font-medium text-muted-foreground shrink-0">Viewing as:</span>
          <div className="flex items-center gap-2 flex-wrap">
            <Select
              value={viewTeamId}
              onValueChange={(v) => { setViewTeamId(v); if (v !== "__all__") setViewUserId("__all__"); }}
            >
              <SelectTrigger className="h-8 text-xs w-[160px]" data-testid="select-view-team">
                <div className="flex items-center gap-1.5">
                  <Users className="h-3.5 w-3.5 text-muted-foreground" />
                  <SelectValue placeholder="All Teams" />
                </div>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">All Teams</SelectItem>
                {teamsList.map(t => (
                  <SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select
              value={viewUserId}
              onValueChange={(v) => { setViewUserId(v); if (v !== "__all__") setViewTeamId("__all__"); }}
            >
              <SelectTrigger className="h-8 text-xs w-[180px]" data-testid="select-view-user">
                <SelectValue placeholder="All Employees" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="__all__">All Employees</SelectItem>
                {userDirectory.map(u => (
                  <SelectItem key={u.id} value={u.id}>
                    {u.firstName || u.lastName ? `${u.firstName ?? ""} ${u.lastName ?? ""}`.trim() : u.email}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {(viewTeamId !== "__all__" || viewUserId !== "__all__") && (
              <button
                onClick={() => { setViewTeamId("__all__"); setViewUserId("__all__"); }}
                className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1"
                data-testid="button-clear-view-filter"
              >
                <X className="h-3.5 w-3.5" /> Clear
              </button>
            )}
          </div>
          {viewTeamId !== "__all__" && (
            <span className="text-xs text-primary font-medium ml-auto">
              {teamsList.find(t => String(t.id) === viewTeamId)?.name ?? ""}
            </span>
          )}
          {viewUserId !== "__all__" && (
            <span className="text-xs text-primary font-medium ml-auto">
              {(() => {
                const u = userDirectory.find(u => u.id === viewUserId);
                return u ? (u.firstName || u.lastName ? `${u.firstName ?? ""} ${u.lastName ?? ""}`.trim() : u.email) : "";
              })()}
            </span>
          )}
        </div>
      )}

      {/* ── Top Strip: 4 Stat Cards ──────────────────────────────────── */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {/* Greeting */}
        <Card className="shadow-sm border-border/40 bg-card order-first md:order-last">
          <CardContent className="p-4 flex flex-col justify-between h-full">
            <div className="flex items-center gap-2 text-muted-foreground mb-1">
              <Sun className="h-4 w-4 text-amber-500" />
              <span className="text-xs font-medium">{format(now, "EEEE, MMM d")}</span>
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">{greeting},</p>
              <p className="text-xl font-heading font-bold text-primary">{firstName}</p>
            </div>
          </CardContent>
        </Card>

        {/* At-Risk Accounts */}
        <Card className="shadow-sm border-red-200 bg-red-50 dark:bg-red-950/20 dark:border-red-900/40">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="text-[11px] font-medium text-red-700 dark:text-red-400 uppercase tracking-wider flex items-center gap-1.5">
              <AlertTriangle className="h-3.5 w-3.5 shrink-0" />
              Accounts At Risk
            </CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4">
            <div className="text-3xl font-heading font-bold text-red-700 dark:text-red-400" data-testid="text-at-risk-count">
              {atRiskCount}
            </div>
            <p className="text-xs text-red-600/70 dark:text-red-400/70 mt-1">score below 40</p>
          </CardContent>
        </Card>

        {/* Declining Accounts */}
        <Card className="shadow-sm border-orange-200 bg-orange-50 dark:bg-orange-950/20 dark:border-orange-900/40">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="text-[11px] font-medium text-orange-700 dark:text-orange-400 uppercase tracking-wider flex items-center gap-1.5">
              <TrendingDown className="h-3.5 w-3.5 shrink-0" />
              Declining
            </CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4">
            <div className="text-3xl font-heading font-bold text-orange-700 dark:text-orange-400" data-testid="text-declining-count">
              {decliningCount}
            </div>
            <p className="text-xs text-orange-600/70 dark:text-orange-400/70 mt-1">trend declining</p>
          </CardContent>
        </Card>

        {/* Overdue Tasks */}
        <Card className="shadow-sm border-amber-200 bg-amber-50 dark:bg-amber-950/20 dark:border-amber-900/40">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="text-[11px] font-medium text-amber-700 dark:text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
              <Clock className="h-3.5 w-3.5 shrink-0" />
              Overdue Tasks
            </CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4">
            <div className="text-3xl font-heading font-bold text-amber-700 dark:text-amber-400" data-testid="text-overdue-count">
              {overdueTasks.length}
            </div>
            <p className="text-xs text-amber-600/70 dark:text-amber-400/70 mt-1">
              {overdueTasks.length === 0 ? "all caught up" : "past due date"}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* ── Onboarding Card ─────────────────────────────────────────── */}
      {showOnboarding && (
        <Card className="border-primary/20 bg-primary/5 shadow-sm relative overflow-hidden">
          <Button
            variant="ghost"
            size="icon"
            className="absolute top-2 right-2 h-8 w-8 text-muted-foreground hover:text-foreground z-10"
            onClick={dismissOnboarding}
            data-testid="button-dismiss-onboarding"
          >
            <X className="h-4 w-4" />
          </Button>
          <CardHeader className="pb-3">
            <CardTitle className="text-xl font-heading flex items-center gap-2">
              <Trophy className="h-5 w-5 text-primary" />
              Getting Started
              <span className="ml-2 text-sm font-normal text-primary">{completedCount}/4 complete</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {onboardingItems.map((item) => (
                <div
                  key={item.id}
                  className={cn("flex flex-col p-4 rounded-lg border bg-card transition-all hover:shadow-md", item.done ? "border-primary/20 bg-primary/5" : "border-border")}
                  data-testid={`onboarding-step-${item.id}`}
                >
                  <div className="flex items-center justify-between mb-3">
                    <div className={cn("p-2 rounded-md", item.done ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground")}>
                      <item.icon className="h-5 w-5" />
                    </div>
                    <Button variant="ghost" size="icon" className="h-6 w-6 p-0" onClick={() => toggleStep(item.id)} data-testid={`button-toggle-step-${item.id}`}>
                      {item.done ? <CheckCircle2 className="h-5 w-5 text-primary" /> : <Circle className="h-5 w-5 text-muted-foreground" />}
                    </Button>
                  </div>
                  <h3 className={cn("text-sm font-semibold mb-2", item.done && "text-muted-foreground line-through")}>{item.title}</h3>
                  {item.href ? (
                    <Button variant="outline" size="sm" className="mt-auto w-full text-xs" asChild>
                      <Link href={item.href}>Go to Page</Link>
                    </Button>
                  ) : item.action ? (
                    <Button variant="outline" size="sm" className="mt-auto w-full text-xs" onClick={item.action}>Open Tool</Button>
                  ) : null}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Section 1: Accounts Needing Attention ───────────────────── */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-heading font-semibold">Accounts needing attention</h2>
          <Button variant="ghost" size="sm" asChild className="text-xs text-muted-foreground">
            <Link href="/my-accounts">View all <ArrowRight className="h-3.5 w-3.5 ml-1" /></Link>
          </Button>
        </div>

        {sortedMyClients.length === 0 ? (
          <Card className="shadow-sm border-border/40">
            <CardContent className="py-10 text-center text-muted-foreground text-sm">
              No accounts assigned to you yet.
            </CardContent>
          </Card>
        ) : (
          <Card className="shadow-sm border-border/40 overflow-hidden">
            <div className="divide-y divide-border/40">
              {sortedMyClients.slice(0, 15).map((client) => {
                const isPhase1 = (client.customerPhase ?? 1) === 1 || client.healthScore === null;
                const milestoneData = isPhase1 ? (milestoneSummary[client.id] ?? { completed: 0, total: 7 }) : { completed: 0, total: 7 };
                const lastContactDate = client.lastContactDate ? new Date(client.lastContactDate) : null;
                const lastContactLabel = lastContactDate
                  ? isToday(lastContactDate) ? "Today"
                  : isYesterday(lastContactDate) ? "Yesterday"
                  : formatDistanceToNow(lastContactDate, { addSuffix: true })
                  : "Never";
                const action = getSuggestedAction(client, openQuoteClientIds);

                return (
                  <div
                    key={client.id}
                    className="flex items-center gap-3 px-4 py-3 hover:bg-muted/30 transition-colors cursor-pointer group"
                    onClick={() => setLocation(`/customers/${client.id}`)}
                    data-testid={`row-account-${client.id}`}
                  >
                    {/* Customer name */}
                    <div className="min-w-0 flex-1">
                      <p className="font-semibold text-sm truncate">{client.name}</p>
                      <p className="text-xs text-muted-foreground truncate">
                        {client.industry ?? "—"}
                      </p>
                    </div>

                    {/* Health or Onboarding */}
                    <div className="shrink-0 flex items-center gap-1.5">
                      {isPhase1 ? (
                        <div className="flex items-center gap-1.5">
                          <Badge className="bg-blue-100 text-blue-700 border-blue-200 text-[10px]" data-testid={`badge-onboarding-${client.id}`}>
                            New
                          </Badge>
                          <span className="text-[10px] text-muted-foreground font-medium" data-testid={`text-milestone-count-${client.id}`}>{milestoneData.completed}/{milestoneData.total}</span>
                        </div>
                      ) : (
                        <div className="flex items-center gap-1">
                          <span className={cn("text-[11px] font-bold px-2 py-0.5 rounded-full", getHealthColor(client.healthScore))} data-testid={`badge-health-${client.id}`}>
                            {client.healthScore}
                          </span>
                          <TrendArrow trend={client.healthTrend} />
                        </div>
                      )}
                    </div>

                    {/* Last contact - hidden on small screens */}
                    <div className="shrink-0 hidden md:flex items-center gap-1 text-xs text-muted-foreground w-24 justify-end">
                      <Calendar className="h-3 w-3 shrink-0" />
                      <span className="truncate">{lastContactLabel}</span>
                    </div>

                    {/* Suggested action chip */}
                    {!isPhase1 && (
                      <div className="shrink-0 hidden lg:block">
                        <span className={cn("text-[10px] font-semibold px-2 py-0.5 rounded-full whitespace-nowrap", action.color)}>
                          {action.label}
                        </span>
                      </div>
                    )}

                    {/* Create task button */}
                    <Button
                      variant="outline"
                      size="sm"
                      className="shrink-0 h-7 text-xs opacity-0 group-hover:opacity-100 transition-opacity"
                      onClick={(e) => {
                        e.stopPropagation();
                        createTaskMutation.mutate({
                          title: `Follow up with ${client.name}`,
                          relatedClientId: client.id,
                          priority: client.healthScore !== null && client.healthScore < 40 ? "high" : "medium",
                        });
                      }}
                      disabled={createTaskMutation.isPending}
                      data-testid={`button-create-task-${client.id}`}
                    >
                      <Plus className="h-3 w-3 mr-1" />
                      Task
                    </Button>
                  </div>
                );
              })}
            </div>
            {sortedMyClients.length > 15 && (
              <div className="px-4 py-3 border-t border-border/40 text-center">
                <Button variant="ghost" size="sm" asChild className="text-xs text-muted-foreground">
                  <Link href="/my-accounts">View all {sortedMyClients.length} accounts</Link>
                </Button>
              </div>
            )}
          </Card>
        )}
      </div>

      {/* ── Overdue Onboarding Milestones ─────────────────────────────── */}
      {overdueMilestones.length > 0 && (
        <Card className="shadow-sm border-amber-200 dark:border-amber-900/50 bg-amber-50/40 dark:bg-amber-950/10" data-testid="card-overdue-milestones">
          <button
            className="flex items-center justify-between w-full text-left px-4 py-3"
            onClick={() => setOverdueMilestonesExpanded(v => !v)}
            data-testid="button-toggle-overdue-milestones"
          >
            <div className="flex items-center gap-2">
              <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-amber-500 shrink-0" />
              <span className="text-sm font-semibold text-amber-800 dark:text-amber-400">
                New customer onboarding — {overdueMilestones.reduce((s, c) => s + c.overdueCount, 0)} milestone{overdueMilestones.reduce((s, c) => s + c.overdueCount, 0) !== 1 ? "s" : ""} overdue across {overdueMilestones.length} customer{overdueMilestones.length !== 1 ? "s" : ""}
              </span>
            </div>
            {overdueMilestonesExpanded
              ? <ChevronUp className="h-4 w-4 text-amber-600 dark:text-amber-500 shrink-0" />
              : <ChevronDown className="h-4 w-4 text-amber-600 dark:text-amber-500 shrink-0" />}
          </button>
          {overdueMilestonesExpanded && (
            <div className="border-t border-amber-200 dark:border-amber-900/50 divide-y divide-amber-100 dark:divide-amber-900/30">
              {overdueMilestones.map(item => (
                <div
                  key={item.clientId}
                  className="flex items-center gap-3 px-4 py-2.5 hover:bg-amber-100/60 dark:hover:bg-amber-900/20 transition-colors cursor-pointer"
                  onClick={() => setLocation(`/customers/${item.clientId}`)}
                  data-testid={`row-overdue-milestones-${item.clientId}`}
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{item.clientName}</p>
                  </div>
                  <span className="text-xs font-semibold text-red-600 dark:text-red-400 whitespace-nowrap" data-testid={`text-overdue-count-${item.clientId}`}>
                    {item.overdueCount} overdue
                  </span>
                  <ArrowRight className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                </div>
              ))}
            </div>
          )}
        </Card>
      )}

      {/* ── Section 2: Today's Alerts ────────────────────────────────── */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-heading font-semibold flex items-center gap-2">
            <BellRing className="h-5 w-5 text-primary" />
            Today's alerts
          </h2>
          {todaysAlerts.length > 0 && (
            <Button variant="ghost" size="sm" asChild className="text-xs text-muted-foreground">
              <Link href="/tasks">View tasks <ArrowRight className="h-3.5 w-3.5 ml-1" /></Link>
            </Button>
          )}
        </div>

        {tasksLoading ? (
          <Card className="shadow-sm border-border/40"><CardContent className="py-4 space-y-2">{[1,2,3].map(i => <Skeleton key={i} className="h-10 w-full" />)}</CardContent></Card>
        ) : todaysAlerts.length === 0 ? (
          <Card className="shadow-sm border-border/40">
            <CardContent className="py-8 text-center">
              <CheckCircle2 className="h-8 w-8 text-green-500 mx-auto mb-2" />
              <p className="text-sm font-medium text-foreground">No alerts today — all accounts look good.</p>
              <p className="text-xs text-muted-foreground mt-1">The overnight health check didn't find anything urgent.</p>
            </CardContent>
          </Card>
        ) : (
          <Card className="shadow-sm border-border/40 overflow-hidden">
            <div className="divide-y divide-border/40">
              {todaysAlerts.map((task) => {
                const alertType = getAlertType(task.title);
                const alertColor = ALERT_COLORS[alertType] ?? "bg-muted text-muted-foreground border-muted";
                const linkedClient = task.relatedClientId ? clientMap[task.relatedClientId] : null;

                return (
                  <div key={task.id} className="flex items-center gap-3 px-4 py-3" data-testid={`alert-task-${task.id}`}>
                    <Badge variant="outline" className={cn("text-[10px] font-bold shrink-0 border", alertColor)}>
                      {alertType}
                    </Badge>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{task.title}</p>
                    </div>
                    {linkedClient && (
                      <Button variant="ghost" size="sm" className="shrink-0 h-7 text-xs" asChild>
                        <Link href={`/customers/${linkedClient.id}`}>
                          View <ArrowRight className="h-3 w-3 ml-1" />
                        </Link>
                      </Button>
                    )}
                  </div>
                );
              })}
            </div>
          </Card>
        )}
      </div>

      {/* ── Section 3: Pipeline & Revenue (Collapsible) ──────────────── */}
      <Card className="shadow-sm border-border/40">
        <CardHeader className="pb-3">
          <button
            className="flex items-center justify-between w-full text-left"
            onClick={() => setPipelineExpanded(v => !v)}
            data-testid="button-toggle-pipeline"
          >
            <div className="flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
              <span className="font-heading font-semibold">Pipeline &amp; revenue overview</span>
            </div>
            {pipelineExpanded ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
          </button>
        </CardHeader>

        {pipelineExpanded && (
          <CardContent className="pt-0">
            <div className="grid gap-6 md:grid-cols-2">
              {/* Revenue Chart */}
              <div>
                <p className="text-sm font-semibold mb-3">Revenue Trend — last 12 months</p>
                {statsLoading ? (
                  <Skeleton className="h-40 w-full" />
                ) : (
                  <ResponsiveContainer width="100%" height={160}>
                    <BarChart data={chartData} margin={{ top: 4, right: 4, left: 0, bottom: 0 }}>
                      <XAxis dataKey="month" tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} />
                      <YAxis tickFormatter={formatShortCurrency} tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} width={48} />
                      <Tooltip
                        formatter={(v: number) => [formatCurrency(v), "Revenue"]}
                        contentStyle={{ fontSize: 12, border: "1px solid var(--border)", borderRadius: 8, background: "var(--background)", color: "var(--foreground)" }}
                      />
                      <Bar dataKey="revenue" fill="#BE1916" radius={[4, 4, 0, 0]} maxBarSize={48} />
                    </BarChart>
                  </ResponsiveContainer>
                )}
              </div>

              {/* Pipeline Stage Breakdown */}
              <div>
                <p className="text-sm font-semibold mb-3">Pipeline Stage Breakdown</p>
                {statsLoading ? (
                  <div className="space-y-3">{[1,2,3].map(i => <Skeleton key={i} className="h-6 w-full" />)}</div>
                ) : (
                  <div className="space-y-2.5">
                    {(stats?.leadStageCounts ?? [])
                      .filter(item => !["won", "lost"].includes(item.stage))
                      .map(item => (
                        <div key={item.stage} className="space-y-1">
                          <div className="flex items-center justify-between text-xs">
                            <span className="font-medium">{STAGE_LABELS[item.stage] ?? item.stage}</span>
                            <span className="text-muted-foreground tabular-nums">{item.count}</span>
                          </div>
                          <div className="h-1.5 w-full bg-muted rounded-full overflow-hidden">
                            <div
                              className="h-full bg-primary transition-all"
                              style={{ width: `${Math.max((item.count / (Number(stats?.activeLeads ?? 1) || 1)) * 100, item.count > 0 ? 3 : 0)}%` }}
                            />
                          </div>
                        </div>
                      ))}
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        )}
      </Card>
    </div>
  );
}
